######################################################################
# Automatically generated by qmake (3.0) ?? 5? 9 07:04:53 2017
######################################################################
QT     += concurrent

TEMPLATE = app
TARGET = rtmp_test
INCLUDEPATH += .

# Input
HEADERS += RTMPStream.h SpsDecode.h
SOURCES += RTMPStream.cpp \
    main.cpp



INCLUDEPATH += -I/usr/include


LIBS += -L/usr/lib -lrtmp


#INCLUDEPATH += -I/opt/yogurt/i.MX6-PD15.3.0/sysroots/cortexa9hf-vfp-neon-phytec-linux-gnueabi/usr/include


#LIBS += -L/opt/yogurt/i.MX6-PD15.3.0/sysroots/cortexa9hf-vfp-neon-phytec-linux-gnueabi/usr/lib -lrtmp

DISTFILES += \
    readme.md

